sources:
  - Glyphs-decomposed-for-export/GF-Foldit.glyphs
  outputDir: "../fonts"
    ttfDir: "../fonts/ttf"
    # otfDir: "../../fonts/otf"
    # woffDir: "../../fonts/woff"
    # varDir: "../../fonts/var"
    # buildOTF: False
familyName: Foldit
axisOrder:
      - wght
      - wdth
      # - colr
stat:
 - name: Weight and width masters
        tag: wght, wdth
        values:
        - name: Thin
          value: 100, 75
        - name: ExtraBold
          value: 800, 125
# instances:
#   Foldit[wght, width].ttf:
#   - familyName: "Foldit"
#     styleName: "Thin Condensed"
#     coordinates:
#       wght: 100
#       wdth: 75
#   - familyName: "Foldit"
#     styleName: "ExtraBold Expanded"
#     coordinates:
#       wght: 800
#       wdth: 125
